
services:
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myapp/nginx
    container_name: webserver
    ports:
      - "80:80"
    volumes: 
      - ./code:/data/application.local
      - ./nginx/conf/nginx/hosts:/etc/nginx/sites-enabled/
    networks:
      - app-network

  app:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: myapp/php
    container_name: app
    volumes:
      - ./code:/data/application.local
      - ./fpm/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  db: 
    build:
      context: ./db
      dockerfile: Dockerfile
      args: 
        - MY_CNF_FILE=my.cnf
    image: myapp/mysql
    container_name: db
    ports:
      - "3306:3306"
      - "3307:3306"
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      # - ./db/my.cnf:/etc/my.cnf
      - ./dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge